#!/usr/bin/env python3
"""Generate the embedded firmware init block for c930/synth/c930_ddr_stub.sv.

Reads a raw binary image (sw/npu_boot.bin), pads it to the 512-byte stub
window (16 lines x 32 B), and prints the Verilog initial block that loads
mem[0..15]. mem[i] bit 0 corresponds to image byte at offset i*32.

Usage: python3 sw/gen_stub_init.py <in.bin>
       (prints the initial block to stdout for inlining into the stub)
"""
import sys


def main(argv):
    if len(argv) != 2:
        print(f"usage: {argv[0]} <in.bin>", file=sys.stderr)
        return 1
    with open(argv[1], "rb") as f:
        data = f.read()
    data = data[:512].ljust(512, b"\x00")
    # Bank-interleaved storage: 8 banks x 16 lines x 32-bit words. Line L's
    # bytes [k*4 +: 4] live in mem[k][L]. Bank format keeps the stub
    # BRAM-mappable (each bank is a 1R1W 16x32 array); the FF line-array
    # version cost ~5K LUTs of write-decode muxes and blew the A7-35T budget.
    print("// 512-byte boot image, bank-interleaved (8 banks x 16 lines x 32b).")
    print("// mem[k][L] = 32 bits at line L, bytes [k*4 +: 4].")
    print("// Auto-generated by sw/gen_stub_init.py -- DO NOT EDIT.")
    print("initial begin")
    for i in range(16):
        line = data[i * 32:(i + 1) * 32]
        # 256-bit line literal: leftmost hex char = MSB (byte 31), rightmost = byte 0.
        h = line[::-1].hex()
        print(f"  // line {i:2d} = 256'h{h}")
        for k in range(8):
            word = line[k * 4:(k + 1) * 4]
            w = word[::-1].hex()
            print(f"  mem[{k}][{i:2d}] = 32'h{w};")
    print("end")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
