// -----------------------------------------------------------------------------
// c930_systolic_array.sv
//
// Weight-stationary systolic array: NUM_ROWS x NUM_COLS grid of PEs.
//
//   * Weights are loaded one PE per cycle through the (i_wrow, i_wcol) address.
//   * Activations enter on the left edge (i_act, one per row) and propagate
//     left -> right.
//   * Partial sums enter on the top edge (i_ps_in, one per column) and
//     propagate top -> bottom; completed results exit at o_ps_out.
//
// Skew (row-k activation pulse delayed by k, column-n accumulator pulse
// delayed by n) is generated by the controller and is NOT part of this module,
// keeping the mesh clean.
//
// The i_precision signal is broadcast to all PEs to select between:
//   - INT8/INT16 integer MAC (precision 0/1)
//   - FP16 floating-point MAC (precision 2)
// -----------------------------------------------------------------------------

module c930_systolic_array
#(
  parameter int NUM_ROWS = 8,   // reduction length per pass
  parameter int NUM_COLS = 8,   // output width
  parameter int DIN_W    = 8,   // activation / weight width
  parameter int ACC_W    = 32   // accumulator width
)
(
  input  logic                                     i_clk,
  input  logic                                     i_rst_n,

  // Weight load: one PE per cycle, addressed by (row, col)
  input  logic                                     i_wen,
  input  logic [$clog2(NUM_ROWS)-1:0]              i_wrow,
  input  logic [$clog2(NUM_COLS)-1:0]              i_wcol,
  input  logic signed [DIN_W-1:0]                  i_wdata,

  // Left-edge activations (one per row): flattened like o_ps_out -- row r
  // lives in bits [r*DIN_W +: DIN_W] (unpacked-array ports misconnect in
  // Icarus 11 and are rejected by yosys's SV parser).
  input  logic signed [NUM_ROWS*DIN_W-1:0]         i_act,
  // Top-edge partial sums (one per column): col c lives in bits [c*ACC_W +: ACC_W]
  input  logic signed [NUM_COLS*ACC_W-1:0]         i_ps_in,

  // Bottom-edge partial sums (one per column): completed outputs.
  // Flattened into one packed vector: Icarus 11 misconnects unpacked-array
  // output ports, so column c lives in bits [c*ACC_W +: ACC_W].
  output signed [ACC_W*NUM_COLS-1:0]               o_ps_out,

  // Precision control: broadcast to all PEs
  input  logic [1:0]                               i_precision
);

  // Horizontal activation buses: a_h[r][c] enters PE(r,c); a_h[r][NUM_COLS] is
  // the right-edge output (unused).
  logic signed [DIN_W-1:0] a_h [0:NUM_ROWS-1][0:NUM_COLS];

  // Vertical partial-sum buses: ps_v[r][c] enters PE(r,c); ps_v[NUM_ROWS][c] is
  // the bottom-edge output.
  logic signed [ACC_W-1:0] ps_v [0:NUM_ROWS][0:NUM_COLS-1];

  generate
    genvar r, c;
    for (r = 0; r < NUM_ROWS; r = r + 1) begin : g_row
      assign a_h[r][0] = i_act[r*DIN_W +: DIN_W];
      for (c = 0; c < NUM_COLS; c = c + 1) begin : g_col
        c930_tensor_pe #(
          .DIN_W (DIN_W),
          .ACC_W (ACC_W)
        ) u_pe (
          .i_clk      (i_clk),
          .i_rst_n    (i_rst_n),
          .i_wen      (i_wen &&
                       (i_wrow == r[$clog2(NUM_ROWS)-1:0]) &&
                       (i_wcol == c[$clog2(NUM_COLS)-1:0])),
          .i_wdata    (i_wdata),
          .i_a_in     (a_h[r][c]),
          .o_a_out    (a_h[r][c+1]),
          .i_ps_in    (ps_v[r][c]),
          .o_ps_out   (ps_v[r+1][c]),
          .i_precision(i_precision)
        );
      end
    end
    for (c = 0; c < NUM_COLS; c = c + 1) begin : g_edge
      assign ps_v[0][c]                     = i_ps_in[c*ACC_W +: ACC_W];
      assign o_ps_out[c*ACC_W +: ACC_W]     = ps_v[NUM_ROWS][c];
    end
  endgenerate

endmodule
