## ---------------------------------------------------------------------------
## DDR3L timing constraints for Arty A7-100T
##
## The DDR3L physical pin assignments (ddr3_dq, ddr3_addr, ddr3_ck, etc.)
## are automatically generated by the MIG 7 Series IP when you create the
## IP in Vivado.  They live inside the mig_7series_0.xci and are applied
## when the IP's XDC is included in the project.
##
## This file adds timing constraints that apply ON TOP of the MIG IP's
## own constraints — specifically for the clock-domain crossing between
## the SoC's core_clk and the MIG's ui_clk.
## ---------------------------------------------------------------------------

## ---- False paths between core_clk and MIG ui_clk ----
## The cache↔AXI4 bridge uses toggle synchronisers for CDC.
## These false paths tell Vivado not to try to meet timing across the
## clock domain boundary (the synchronisers handle it).
set_false_path -from [get_clocks -of_objects [get_ports {i_clk}]] \
               -to   [get_clocks -of_objects [get_ports {ui_clk}]]
set_false_path -from [get_clocks -of_objects [get_ports {ui_clk}]] \
               -to   [get_clocks -of_objects [get_ports {i_clk}]]

## ---- MIG calibration complete ----
## The init_calib_complete signal from MIG is used as a reset gate.
## Treat it as a quasi-static signal (changes once after calibration).
set_false_path -from [get_ports {init_calib_complete}]
