#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# run_yosys_xilinx.sh  --  Run Yosys synth_xilinx for C930 SoC
#
# Gives Xilinx-mapped LUT/FF/DSP/BRAM counts without Vivado.
# Usage:  bash synth_xilinx/run_yosys_xilinx.sh
# ---------------------------------------------------------------------------
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OSS="$HERE/../toolchain/oss-cad-suite"
OUT="$HERE/../build/synth_xilinx"

if [ ! -x "$OSS/bin/yosys.exe" ]; then
    echo "ERROR: oss-cad-suite not found at $OSS" >&2
    exit 1
fi

# cmd needs the oss-cad-suite bin/lib dirs on PATH to find its DLLs.
export PATH="$OSS/bin:$OSS/lib:$PATH"

mkdir -p "$OUT"

cd "$HERE/.."   # c930/ -- keep all paths relative

# Build the file list dynamically (same as Makefile wildcard)
CORE_FILES=$(ls ../rv64imac/RTL/*.sv | tr '\n' ' ')
NPU_FILES="rtl/c930_tensor_pe.sv rtl/c930_systolic_array.sv rtl/c930_npu_core.sv rtl/c930_npu_csr.sv rtl/c930_npu_dma.sv rtl/c930_npu_top.sv rtl/c930_mmio_bridge.sv rtl/c930_soc_top.sv synth/c930_ddr_stub.sv"

# Generate the Yosys script dynamically
cat > build/synth_xilinx/run_xilinx.ys <<YSEOF
# Auto-generated by run_yosys_xilinx.sh
read_verilog -sv $CORE_FILES $NPU_FILES
synth_xilinx -flatten -top c930_soc_top
stat
YSEOF

echo "== Yosys synth_xilinx (c930_soc_top, Xilinx Artix-7 target) =="
cmd //c "yosys -ql build/synth_xilinx/xilinx_synth.log build/synth_xilinx/run_xilinx.ys"

echo ""
echo "=== LATCHES ==="
grep -c "Latch" build/synth_xilinx/xilinx_synth.log 2>/dev/null || echo "(none)"
grep "Latch" build/synth_xilinx/xilinx_synth.log 2>/dev/null | head -10 || true

echo ""
echo "=== RESOURCE ESTIMATE (Xilinx-mapped) ==="
# The stat output is in the log; extract the summary
grep -A 30 "Printing statistics" build/synth_xilinx/xilinx_synth.log | tail -30

echo ""
echo "Done. Full log: build/synth_xilinx/xilinx_synth.log"
