## ==========================================================================
## xc7a200t_nexys_video.xdc  --  Nexys Video Rev. A pin constraints
## for the c930 SoC  (xc7a200tfbg484-1)
## ==========================================================================
## Usage: replace xc7a200t_clock.xdc with this file in create_project.tcl
##        (or add both; the more-specific file wins on overlap).
## ==========================================================================

## ---- Configuration voltage ----
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

## ---- 100 MHz system clock (R4, LVCMOS33) ----
set_property -dict { PACKAGE_PIN R4  IOSTANDARD LVCMOS33 } [get_ports { i_clk }]
create_clock -name sys_clk -period 10.000 [get_ports { i_clk }]

## ---- CPU reset (active-low, G4, LVCMOS15) ----
set_property -dict { PACKAGE_PIN G4  IOSTANDARD LVCMOS15 } [get_ports { i_rst_n }]

## ---- Core clock: 100 MHz / CLK_DIV=2 -> 50 MHz ----
## Generated by the BUFG divider inside g_clkgen.
create_generated_clock -name core_clk \
    -source [get_ports {i_clk}] \
    -divide_by 2 \
    [get_pins g_clkgen.clk_div_reg/Q]

## ---- UART (directly to FTDI USB bridge, no flow control) ----
## SoC TX  -> FTDI RX  (AA19, LVCMOS33)
## FTDI TX -> SoC RX  (V18,  LVCMOS33)
set_property -dict { PACKAGE_PIN AA19 IOSTANDARD LVCMOS33 } [get_ports { o_uart_txd }]
set_property -dict { PACKAGE_PIN V18  IOSTANDARD LVCMOS33 } [get_ports { i_uart_rxd }]

## ---- NPU0 status LEDs (active-high) ----
##   led[0] = o_npu_busy    (T14)
##   led[1] = o_npu_done    (T15)
##   led[2] = o_npu_error   (T16)
##   led[3] = o_npu_irq     (U16)
set_property -dict { PACKAGE_PIN T14 IOSTANDARD LVCMOS25 } [get_ports { o_npu_busy  }]
set_property -dict { PACKAGE_PIN T15 IOSTANDARD LVCMOS25 } [get_ports { o_npu_done  }]
set_property -dict { PACKAGE_PIN T16 IOSTANDARD LVCMOS25 } [get_ports { o_npu_error }]
set_property -dict { PACKAGE_PIN U16 IOSTANDARD LVCMOS25 } [get_ports { o_npu_irq   }]

## ---- NPU1 status LEDs ----
##   led[4] = o_npu1_busy   (V15)
##   led[5] = o_npu1_done   (W16)
##   led[6] = o_npu1_error  (W15)
##   led[7] = o_npu1_irq    (Y13)
set_property -dict { PACKAGE_PIN V15 IOSTANDARD LVCMOS25 } [get_ports { o_npu1_busy  }]
set_property -dict { PACKAGE_PIN W16 IOSTANDARD LVCMOS25 } [get_ports { o_npu1_done  }]
set_property -dict { PACKAGE_PIN W15 IOSTANDARD LVCMOS25 } [get_ports { o_npu1_error }]
set_property -dict { PACKAGE_PIN Y13 IOSTANDARD LVCMOS25 } [get_ports { o_npu1_irq   }]

## ---- Switches (active-high, direct to SoC as config inputs) ----
##   sw[0] = E22, sw[1] = F21, sw[2] = G21, sw[3] = G22
##   sw[4] = H17, sw[5] = J16, sw[6] = K13, sw[7] = M17
## Uncomment and rename if you add sw inputs to the top module:
# set_property -dict { PACKAGE_PIN E22 IOSTANDARD LVCMOS12 } [get_ports { sw[0] }]
# set_property -dict { PACKAGE_PIN F21 IOSTANDARD LVCMOS12 } [get_ports { sw[1] }]
# set_property -dict { PACKAGE_PIN G21 IOSTANDARD LVCMOS12 } [get_ports { sw[2] }]
# set_property -dict { PACKAGE_PIN G22 IOSTANDARD LVCMOS12 } [get_ports { sw[3] }]
# set_property -dict { PACKAGE_PIN H17 IOSTANDARD LVCMOS12 } [get_ports { sw[4] }]
# set_property -dict { PACKAGE_PIN J16 IOSTANDARD LVCMOS12 } [get_ports { sw[5] }]
# set_property -dict { PACKAGE_PIN K13 IOSTANDARD LVCMOS12 } [get_ports { sw[6] }]
# set_property -dict { PACKAGE_PIN M17 IOSTANDARD LVCMOS12 } [get_ports { sw[7] }]

## ---- Fan PWM (active-high, directly to the on-board fan) ----
## Uncomment if you add a fan_pwm output:
# set_property -dict { PACKAGE_PIN U15 IOSTANDARD LVCMOS25 } [get_ports { fan_pwm }]

## ---- False paths ----
set_false_path -from [get_ports { i_rst_n }]

## TB preload ports are tie-offs on the board, never real synchronous paths
set_false_path -from [get_ports { i_tb_wr_* }]

## ---- DDR3L (MIG 7 Series) ----
## TODO: Generate MIG IP with Nexys Video memory parameters and connect here.
## The Nexys Video has a 16-bit DDR3L-1600 part (MT41K256M16HA-125).
## Pin assignments will be auto-generated by the MIG IP customization tool.
## Until MIG is integrated, the c930_ddr_stub BRAM model provides 64 KB
## of simulated DDR for firmware boot + test suite.
